# Generated by Django 3.2 on 2021-04-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('usernameDr', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('confirmation', models.CharField(max_length=32)),
                ('emailDr', models.CharField(max_length=60)),
                ('specialization', models.CharField(max_length=500)),
                ('hospital', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
    ]
