# Generated by Django 3.2 on 2021-04-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorReg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorinfo',
            old_name='birth',
            new_name='dob',
        ),
    ]
