# Generated by Django 3.2 on 2021-04-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('confirmation', models.CharField(max_length=32)),
                ('conditions', models.CharField(max_length=500)),
                ('birth', models.DateField()),
            ],
        ),
    ]
