# Generated by Django 3.2 on 2021-04-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('confirmation', models.CharField(max_length=32)),
                ('conditions', models.CharField(max_length=500)),
                ('birth', models.DateField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('drname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('approval', models.CharField(max_length=100)),
                ('done', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('usernameDr', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('confirmation', models.CharField(max_length=32)),
                ('emailDr', models.CharField(max_length=60)),
                ('specialization', models.CharField(max_length=500)),
                ('hospital', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
    ]
