# Generated by Django 3.2 on 2021-04-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('confirmation', models.CharField(max_length=32)),
                ('emailDr', models.CharField(max_length=60)),
                ('specialization', models.CharField(max_length=500)),
                ('hospital', models.CharField(max_length=100)),
            ],
        ),
    ]
