# Generated by Django 3.2 on 2021-04-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_doctorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('drname', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
