# Generated by Django 3.2 on 2021-04-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_confirmedappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedappointment',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
