# Generated by Django 3.2 on 2021-04-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_confirmedappointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='username',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confirmedappointment',
            name='time',
            field=models.DateField(),
        ),
    ]
