# Generated by Django 3.2 on 2021-04-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20210425_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedappointment',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
