# Generated by Django 3.2 on 2021-04-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_alter_confirmedappointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedappointment',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
