# Generated by Django 3.2 on 2021-04-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_alter_confirmedappointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
