# Generated by Django 3.2 on 2021-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_alter_clientinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='dob',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='usernameDr',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
