# Generated by Django 3.2 on 2021-04-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_auto_20210426_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedappointment',
            name='approval',
            field=models.CharField(default='pending', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmedappointment',
            name='done',
            field=models.CharField(default='no', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmedappointment',
            name='link',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmedappointment',
            name='username',
            field=models.CharField(default='-', max_length=30),
            preserve_default=False,
        ),
    ]
