# Generated by Django 3.2 on 2021-04-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_auto_20210426_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedappointment',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
