# Generated by Django 3.2 on 2021-04-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientReg', '0003_auto_20210425_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
